#!/bin/bash
# ---------------------------------------------------------------
# New Machine Setup Script.
# ---------------------------------------------------------------
# This script must be idempotent!
set -eEo pipefail
set -x

# ---------------------------------------------------------------
# Install vim.
# ---------------------------------------------------------------
sudo apt install vim

# ---------------------------------------------------------------
# Set locale.
# ---------------------------------------------------------------
echo "Setting locale (requires password)..."
sudo locale-gen en_US.UTF-8

# ---------------------------------------------------------------
# Create home folder structure.
# ---------------------------------------------------------------
mkdir -p ~/bin

# ---------------------------------------------------------------
# Acquire ssh keys and config.
# ---------------------------------------------------------------
mkdir -p ~/.ssh
chmod 700 ~/.ssh

hostname='thelio'
template_host_ip=192.168.1.214

echo "Attempting to contact $template_host_ip (may be known as $hostname)"
echo "for SSH keys.  Pinging..."
ping -c1 -q $template_host_ip

echo "Host $hostname is responding; you will now be asked for"
echo "$template_host_ip's ssh password twice."

[[ ! -f ~/.ssh/id_rsa     ]] && scp dsicilia@$template_host_ip:/home/dsicilia/.ssh/id_rsa ~/.ssh
[[ ! -f ~/.ssh/id_rsa.pub ]] && scp dsicilia@$template_host_ip:/home/dsicilia/.ssh/id_rsa.pub ~/.ssh
[[ ! -f ~/.ssh/config ]]     && scp dsicilia@$template_host_ip:/home/dsicilia/.ssh/config ~/.ssh

# ---------------------------------------------------------------
# Install git.
# ---------------------------------------------------------------
echo "Installing git; you may be asked for your account password."
sudo apt install git --yes

# ---------------------------------------------------------------
# Clone dotfiles.
# ---------------------------------------------------------------
clone_impl() {
  local org="$1"
  local repo="$2"
  local where="$3"
  [[ -z "$where" ]] && where="$repo"
  [[ -d "$where" ]] && return 0
  git clone ssh://git@github.com/$org/$repo $where --recursive
  (cd "$where" && fish -c add-gitlab)
}

clone()    { clone_impl fractalminer   "$@"; }
clone_rn() { clone_impl revolution-now "$@"; }

echo "Cloning dotfiles repo; should be passwordless."
cd ~
clone dotfiles .dotfiles

cd ~/.dotfiles
git pull origin master
git submodule update --init

# ---------------------------------------------------------------
# Install Packages.
# ---------------------------------------------------------------
echo "Installing packages."
cd ~/.dotfiles
scripts/install-packages.sh

# ---------------------------------------------------------------
# Create dev folder and contents.
# ---------------------------------------------------------------
echo "Cloning repos in ~/dev; should be passwordless."
mkdir -p ~/dev
cd ~/dev

clone    calcterm
clone    hexagon
clone    cpp
clone    base-util base/util
clone_rn revolution-now revolution-now
clone_rn revolution-now rn-art
clone_rn revolution-now rn-music
clone    haskell
clone    utilities
clone    suckless
clone    moonlib

# ---------------------------------------------------------------
# Source bashlib
# ---------------------------------------------------------------
source ~/dev/utilities/bashlib/util.sh

# ---------------------------------------------------------------
# VNC
# ---------------------------------------------------------------
mkdir -p ~/.vnc
[[ ! -f ~/.vnc/passwd ]] && scp dsicilia@$linode:/home/dsicilia/.vnc/passwd ~/.vnc/

# ---------------------------------------------------------------
# Setup cmc
# ---------------------------------------------------------------
[[ ! -e ~/bin/cmc ]] && ln -s ~/dev/utilities/cmake/configure ~/bin/cmc

# ---------------------------------------------------------------
# ccache
# ---------------------------------------------------------------
log "Setting ccache size to 100G..."
mkdir -p ~/.ccache
if [[ ! -e ~/.ccache/ccache.conf ]]; then
  echo 'max_size = 100.0G' > ~/.ccache/ccache.conf
fi

# ---------------------------------------------------------------
# redis
# ---------------------------------------------------------------
mkdir -p ~/.local/state/redis

# ---------------------------------------------------------------
# Build Hexagon.
# ---------------------------------------------------------------
cd ~/dev/hexagon
make

# ---------------------------------------------------------------
# Suckless utils.
# ---------------------------------------------------------------
cd ~/dev/suckless
make
./dwm/install.sh

# ---------------------------------------------------------------
# Keyboard shortcuts.
# ---------------------------------------------------------------
log 'Setting gnome workspace switching keybindings...'
~/dev/utilities/keyboard/set-gnome-workspace-shortcuts.sh
log 'Disabling workspace switch animations...'
~/dev/utilities/keyboard/disable-workspace-switch-animation.sh

# ---------------------------------------------------------------
# Wallpapers
# ---------------------------------------------------------------
cd ~
mkdir -p Pictures
cd Pictures
clone wallpapers

#feh --bg-max ~/Pictures/wallpapers/default

# ---------------------------------------------------------------
# Haskell
# ---------------------------------------------------------------
cd ~/.dotfiles
log "Building haskell utils..."
scripts/build-hs-utils.sh

# ---------------------------------------------------------------
# Make `light` work
# ---------------------------------------------------------------
# This allows running /usr/bin/light as root without password, which
# then allows using it to control screen brightness.
log "May need sudo password to give /usr/bin/light +s:"
sudo chmod +s /usr/bin/light

# ---------------------------------------------------------------
# Build vim
# ---------------------------------------------------------------
# We need to do this before running `make` in the dotfiles folder
# since that will update the plugins, and we want the latest vim
# version for that to work.
log "Building nvim..."
~/dev/utilities/building/nvim.sh

# ---------------------------------------------------------------
# Run dotfiles.
# ---------------------------------------------------------------
rm -f ~/.bashrc

log "Running setup scripts."
cd ~/.dotfiles
make

# ---------------------------------------------------------------
# Setup "recycling".
# ---------------------------------------------------------------
log "Creating recycle symlink."
[[ ! -L ~/bin/recycle ]] && ln -s ~/dev/utilities/misc/recycle ~/bin/recycle

# ---------------------------------------------------------------
# Cleaning up tmp files.
# ---------------------------------------------------------------
echo 'Insert this into the root crontab to clean the tmp folder:'
echo '30 11 * * * find /tmp -type f -atime +10 -delete'
echo
echo 'Press enter when done...'
read

# ---------------------------------------------------------------
# rsync from source host.
# ---------------------------------------------------------------
rsync_folder() {
  local dir="$1"
  [[ -d "$dir" ]]
  dir="$(realpath "$dir")"
  echo "rsyncing folder $dir..."
  cd "$dir"
  rsync -avzP "dsicilia@$template_host_ip:$dir/" "$dir/"
}

rsync_folder ~/dev/tools
rsync_folder ~/bin
rsync_folder ~/.local/share/nvim

# ---------------------------------------------------------------
# Finished.
# ---------------------------------------------------------------
log 'Finished.'
